---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: python:3-slim-bullseye
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
