---
# tasks file for myrole

- name: Ensure unbound package installed
  ansible.builtin.package:
    name: unbound
    state: present


- name: Ensure config file is present
  ansible.builtin.copy:
    src: files/unbound.conf
    dest: /etc/unbound/unbound.conf
    owner: root
    group: root
    mode: '0644'


